### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by adarshaj** [navya/Kalam#1]
Please don't check-in binary blobs into git tree. you might instead want to add binary release over [here](https://github.com/navya/Kalam/releases/new). and give instructions on how to build from source in git tree. If you don't wish to share the source then please take it out of navya org.

**Comment by bhanuc** [comment]
Hopefully fixed for now . For now using a shell script to build the generated app.  A bit naive on the scene but will learn soon :)

**Comment by adarshaj** [comment]
cool :+1:
